### PR TITLE
Custom RawRepresentable support

### PR DESCRIPTION
**Pull request by basememara**
I ran into a situation where the compiler allowed me to implement a custom `RawRepresentable` type but crashed at runtime:

```swift
struct TestCustomRepresented: RawRepresentable, UserDefaultsSerializable {
    var rawValue: [String: TestFruit]

    init(rawValue: [String: TestFruit]) {
        self.rawValue = rawValue
    }
}

final class TestSettings {
    @WrappedDefaultOptional(keyName: "customRawRepresented", userDefaults: store)
    var customRawRepresented: TestCustomRepresented?
}
```

When I ran this and tried saving a value to it, I got this crash:

```swift
settings.customRawRepresented = TestCustomRepresented(rawValue: ["key1": .apple])

// =>

libc++abi: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Attempt to insert non-property list object {
    key1 = "FoilTests.TestFruit.apple";
} for key customRawRepresented'
terminating with uncaught exception of type NSException
```

What I ended up doing is fine-tuning the conditional bounds for `Self.RawValue` conformance of `RawRepresentable` and adjusting the implementation:

```swift
// From this:
extension UserDefaultsSerializable where Self: RawRepresentable {
    public var storedValue: RawValue { self.rawValue }

    public init(storedValue: RawValue) {
        self = Self(rawValue: storedValue)!
    }
}

// To this:
extension UserDefaultsSerializable where Self: RawRepresentable, Self.RawValue: UserDefaultsSerializable {
    public var storedValue: RawValue.StoredValue { self.rawValue.storedValue }

    public init(storedValue: RawValue.StoredValue) {
        self = Self(rawValue: Self.RawValue(storedValue: storedValue))!
    }
}
```

This makes sense to leverage `RawRepresentable` this way since according to the [docs](https://developer.apple.com/documentation/swift/rawrepresentable), `RawRepresentable` was designed to interoperate with legacy systems, which `UserDefaults` could be considered:

> Using the raw value of a conforming type streamlines interoperation with Objective-C and legacy APIs..

Doing this opened some interesting doors to `UserDefaults` while allowing existing `RawRepresentable` conformers to remain unchanged:

```swift
struct TestCustomRepresented: RawRepresentable, UserDefaultsSerializable {
    var rawValue: [String: TestFruit]

    init(rawValue: [String: TestFruit]) {
        self.rawValue = rawValue
    }
}

extension TestCustomRepresented {
    enum Key: String {
        case key1, key2, key3
    }

    subscript(_ key: Key) -> TestFruit? {
        get { rawValue[key.rawValue] }
        set { rawValue[key.rawValue] = newValue }
    }
}

settings.customRawRepresented[.key2] = .orange
```

### CODE REVIEW

**Comment by jessesquires** [comment]
This is great 💯 🎉  Nice find @basememara!

**Review by jessesquires — CHANGES_REQUESTED** [review]
Requesting changes to add a changelog entry for this.

I made some updates in #11, so you'll want to rebase on `main` first and then just follow the pattern in the changelog. 😊

**Comment by basememara** [comment]
Cool updated the changelog, let me know if you need any other changes

**Review by jessesquires — APPROVED** [review]
🎉

**Pull request merged**
