### PR TITLE
Add KVO and Combine support to documentation and test

### PR DESCRIPTION
**Pull request by basememara**
Issue #4  

Documents how `Foil` can be used with native KVO and Combine support provided by Apple out of the box.

### CODE REVIEW

**Review by jessesquires — APPROVED** [review]
Wow, this is great. Thanks @basememara! 🥇 💯 

My apologies for taking so long to review. 😊 

Once this gets merged, I'll send you an invite to be a collaborator. 😄

**Comment by jessesquires** [comment]
Hey @basememara -- it looks like tests are failing for iOS/tvOS because the deployment target is 12+.

To fix this, we can set the test target to be 13+. Would you mind doing that here? (If not, I can do it this week.)

(Also, ignore the danger failure. That's a limitation with GH actions.)

**Comment by jessesquires** [comment]
🎉 💯 

thanks again @basememara ! 🙌🏼

**Comment by basememara** [comment]
Np, thx for figuring out why it was failing. I ran it before sleeping and was going to check in the morning. Glad it passed! Thx again for putting all this together!

**Pull request merged**
